# Generated by Django 3.2.5 on 2021-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='writer',
        ),
    ]
