# Generated by Django 3.2.5 on 2021-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='writer',
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(default='untitled', max_length=10, null=True),
        ),
    ]
