# Generated by Django 3.2.5 on 2021-07-23 08:06

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0003_alter_attachment_id'),
        ('memoapp', '0002_auto_20210723_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerNote',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.attachment')),
                ('summer_fields', django_summernote.fields.SummernoteTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
