# Generated by Django 3.2.5 on 2021-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0002_alter_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='favicon_url',
            field=models.URLField(blank=True, verbose_name='favicon_url'),
        ),
    ]
