# Generated by Django 3.2.5 on 2021-07-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0003_bookmark_favicon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='thumbnail',
        ),
    ]
